### ISSUE TITLE
refreshing on the checkout page ends up back to the home page

### ISSUE THREAD

**Issue by mickeyren** [sprangular/sprangular#74] opened 2015-02-12 11:17 UTC
the problem here is on module - https://github.com/sprangular/sprangular/blob/master/app/assets/javascripts/sprangular/module.coffee#L57

Apparently Cart.current.items is empty even if i have line items on my cart:

```ruby
2.1.5 :013 > order = Spree::Order.last
  Spree::Order Load (0.4ms)  SELECT  "spree_orders".* FROM "spree_orders"   ORDER BY "spree_orders"."id" DESC LIMIT 1
 => #<Spree::Order id: 66, number: "R220900179", item_total: #<BigDecimal:7fa35af61710,'0.2998E2',18(18)>, total: #<BigDecimal:7fa35af61648,'0.3578E2',18(18)>, state: "payment", adjustment_total: #<BigDecimal:7fa35af61508,'0.8E0',9(18)>, user_id: 1, completed_at: nil, bill_address_id: 205, ship_address_id: 206, payment_total: #<BigDecimal:7fa35af61210,'0.0',9(18)>, shipping_method_id: nil, shipment_state: nil, payment_state: nil, email: "david@godynamo.com", special_instructions: nil, created_at: "2015-02-11 18:50:58", updated_at: "2015-02-12 11:26:30", currency: "USD", last_ip_address: "127.0.0.1", created_by_id: 1, shipment_total: #<BigDecimal:7fa35af603d8,'0.5E1',9(18)>, additional_tax_total: #<BigDecimal:7fa35af60310,'0.8E0',9(18)>, promo_total: #<BigDecimal:7fa35af60248,'0.0',9(18)>, channel: "spree", included_tax_total: #<BigDecimal:7fa35af60108,'0.0',9(18)>, item_count: 2, approver_id: nil, approved_at: nil, confirmation_delivered: false, considered_risky: false, guest_token: "GXnvvpJnejG1DOWmlRY85g", canceled_at: nil, canceler_id: nil, store_id: 1, state_lock_version: 0, subscription_id: nil, repeat_order: false>
2.1.5 :014 > order.line_items.length
  Spree::LineItem Load (0.4ms)  SELECT "spree_line_items".* FROM "spree_line_items"  WHERE "spree_line_items"."order_id" = $1  ORDER BY spree_line_items.created_at ASC  [["order_id", 66]]
 => 2
```

I don't think the Cart service Cart#load method is being called

**Comment by joshnuss** [comment] 2015-02-15 06:27
@mickey it works for me in the spec/dummy app.

`Cart.load` is actually being called when the `Cart` service is initialized. 

Since the run block takes the `Cart` service as a dependency, `Sprangular.startupData` should of be ran when the service is first created. See:
https://github.com/sprangular/sprangular/blob/master/app/assets/javascripts/sprangular/module.coffee#L37

https://github.com/sprangular/sprangular/blob/master/app/assets/javascripts/sprangular/services/cart.coffee#L111

**Comment by joshnuss** [comment] 2015-02-20 20:19
@mickeyren Can you double check if this is still happening?

**Comment by joshnuss** [comment] 2015-03-05 06:39
Hey @mickeyren,

Confirmed this is working on master

(closing for now, re-open if its still an issue)

**Closed by joshnuss** 2015-03-05 06:39 UTC
